/*
 * Routing OSM
 *
 * With the Routing OSM service you can calculate routes from a list of waypoints based on open street map data.
 *
 * The version of the OpenAPI document: 1.6
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = PTV.Developer.Clients.routing.osm.Client.OpenAPIDateConverter;

namespace PTV.Developer.Clients.routing.osm.Model
{
    /// <summary>
    /// ReachableAreasId
    /// </summary>
    [DataContract(Name = "ReachableAreasId")]
    public partial class ReachableAreasId : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ReachableAreasId" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ReachableAreasId() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ReachableAreasId" /> class.
        /// </summary>
        /// <param name="id">The ID of the calculated reachable areas. (required).</param>
        public ReachableAreasId(Guid? id = default(Guid?))
        {
            // to ensure "id" is required (not null)
            if (id == null)
            {
                throw new ArgumentNullException("id is a required property for ReachableAreasId and cannot be null");
            }
            this.Id = id;
        }

        /// <summary>
        /// The ID of the calculated reachable areas.
        /// </summary>
        /// <value>The ID of the calculated reachable areas.</value>
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public Guid? Id { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ReachableAreasId {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
