/*
 * Routing OSM
 * With the Routing OSM service you can calculate routes from a list of waypoints based on open street map data.
 *
 * The version of the OpenAPI document: 1.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ptvgroup.developer.client.routing_osm.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * The result of the reachable areas calculation.
 */
@ApiModel(description = "The result of the reachable areas calculation.")
@JsonPropertyOrder({
  ReachableAreas.JSON_PROPERTY_POLYGONS
})
@javax.annotation.processing.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-01-15T10:49:31.222161Z[Etc/UTC]")
public class ReachableAreas {
  public static final String JSON_PROPERTY_POLYGONS = "polygons";
  private List<String> polygons = new ArrayList<>();

  public ReachableAreas() { 
  }

  public ReachableAreas polygons(List<String> polygons) {
    this.polygons = polygons;
    return this;
  }

  public ReachableAreas addPolygonsItem(String polygonsItem) {
    this.polygons.add(polygonsItem);
    return this;
  }

   /**
   * The list of polygons calculated for the specified horizons in GeoJson format. For each horizon there is a separate polygon at the same index.
   * @return polygons
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "The list of polygons calculated for the specified horizons in GeoJson format. For each horizon there is a separate polygon at the same index.")
  @JsonProperty(JSON_PROPERTY_POLYGONS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<String> getPolygons() {
    return polygons;
  }


  @JsonProperty(JSON_PROPERTY_POLYGONS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPolygons(List<String> polygons) {
    this.polygons = polygons;
  }


  /**
   * Return true if this ReachableAreas object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ReachableAreas reachableAreas = (ReachableAreas) o;
    return Objects.equals(this.polygons, reachableAreas.polygons);
  }

  @Override
  public int hashCode() {
    return Objects.hash(polygons);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ReachableAreas {\n");
    sb.append("    polygons: ").append(toIndentedString(polygons)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

