/* tslint:disable */
/* eslint-disable */
/**
 * Routing OSM
 * With the Routing OSM service you can calculate routes from a list of waypoints based on open street map data.
 *
 * The version of the OpenAPI document: 1.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CausingError
 */
export interface CausingError {
    /**
     * A human readable message that describes the error.
     * @type {string}
     * @memberof CausingError
     */
    description: string;
    /**
     * A constant string that can be used to identify this error class programmatically.
     * 
     * If additional information is available for an errorCode, it will be provided as key-value pairs with the parameter **details**. The keys available for a specific errorCode are documented directly with the errorCode. Unless stated otherwise, the values are of type string.
     * 
     * As an example, the following errorCode provides one key-value pair in the **details**. The key is called **value**.
     * * `GENERAL_INVALID_VALUE` - A parameter is set to an invalid value.
     *   * `value` - The invalid value.
     * 
     * Note that additional errorCodes as well as the **details** of existing errorCodes may be added at any time. Furthermore, the **description** may change at any time.
     * 
     * **Error codes for** `GENERAL_VALIDATION_ERROR`
     * 
     * * `GENERAL_UNRECOGNIZED_PARAMETER` - A parameter is unknown.
     * * `GENERAL_MISSING_PARAMETER` - A required parameter is missing.
     * * `GENERAL_TYPE_VIOLATED` - The value of a parameter has an invalid type.
     *   * `type` - The type.
     * * `GENERAL_FORMAT_VIOLATED` - The value of a parameter has an invalid format.
     *   * `format` - The format.
     * * `GENERAL_PATTERN_VIOLATED` - The value of a string parameter does not satisfy the required pattern.
     *   * `pattern` - The pattern.
     * * `GENERAL_MINIMUM_LENGTH_VIOLATED` - The minimum length of a string is violated.
     *   * `minimumLength` - The minimum length (integer).
     * * `GENERAL_MAXIMUM_LENGTH_VIOLATED` - The maximum length of a string is violated.
     *   * `maximumLength` - The maximum length (integer).
     * * `GENERAL_MINIMUM_ITEMS_VIOLATED` - The minimum number of items of an array is violated.
     *   * `minimumItems` - The minimum number of items (integer).
     * * `GENERAL_MAXIMUM_ITEMS_VIOLATED` - The maximum number of items of an array is violated.
     *   * `maximumItems` - The maximum number of items (integer).
     * * `GENERAL_MINIMUM_VALUE_VIOLATED` - The minimum value of a parameter is violated.
     *   * `minimumValue` - The minimum value (integer or double).
     * * `GENERAL_MAXIMUM_VALUE_VIOLATED` - The maximum value of a parameter is violated.
     *   * `maximumValue` - The maximum value (integer or double).
     * * `GENERAL_ENUM_VIOLATED` - The value of a parameter is not one of the specified enum values.
     *   * `enum` - The allowed enum values.
     * * `GENERAL_INVALID_VALUE` - A parameter is set to an invalid value.
     *   * `value` - The invalid value.
     * * `GENERAL_DUPLICATE_PARAMETER` - A parameter is duplicated.
     * * `GENERAL_INVALID_LIST` - A list has an invalid format such as duplicate commas.
     *   * `value` - The invalid list.
     * * `ROUTING_INVALID_WAYPOINT_ATTRIBUTE` - A waypoint attribute is set to an invalid value.
     *   * `attribute` - The invalid waypoint attribute.
     * * `ROUTING_UNRECOGNIZED_WAYPOINT_ATTRIBUTE` - A waypoint attribute is unknown.
     *   * `attribute` - The invalid waypoint key.
     * * `ROUTING_DUPLICATE_WAYPOINT_ATTRIBUTE` - A waypoint attribute is duplicated.
     *   * `attribute` - The duplicated waypoint key.
     * * `ROUTING_MUST_HAVE_WAYPOINTS` - The request must have at least two waypoints.
     * * `ROUTING_PROFILE_NOT_FOUND` - The requested profile could not be found.
     *   * `value` - The profile name.
     * * `ROUTING_ESTIMATED_DISTANCE_TOO_LONG` - The distance of the route (estimated by air-line) for non-motorized vehicles is too long. - _The **parameter** remains empty._
     *   * `distance` - The estimated distance (integer).
     *   * `limit` - The maximum allowable distance (integer).
     * * `ROUTING_MAXIMUM_HORIZON_VALUE_VIOLATED` - The maximum value of horizon is violated.
     *   * `limit` - The maximum allowable horizon (integer).
     * 
     * **Error codes for** `ROUTING_ERROR`
     * 
     * * `ROUTING_WAYPOINT_CANNOT_BE_MATCHED` - The waypoint cannot be matched to the nearest possible road.
     * * `ROUTING_ROUTE_NOT_FOUND` - A route between at least two waypoints could not be found for the current configuration and profile. The **parameter** contains the waypoint where the problematic part that could not be routed starts, i.e., the problematic part of the route is between this waypoint and the next one. Note that only the first problematic part that was encountered is reported.
     * 
     * **Error codes for** `ROUTING_RESTRICTION_EXCEEDED`
     * 
     * * `ROUTING_TOO_MANY_WAYPOINTS` - The request contains too many waypoints.
     *   * `limit`- The maximum allowed number of waypoints for a single request (integer).
     * 
     * **Error codes for** `GENERAL_RESOURCE_NOT_FOUND`
     * 
     * * `GENERAL_INVALID_ID` - No resource exists for the provided ID.
     *   * `value` - The ID for which no resource exists.
     * @type {string}
     * @memberof CausingError
     */
    errorCode: string;
    /**
     * The name of the affected query or path parameter or a JSONPath to the affected property of the request.
     * @type {string}
     * @memberof CausingError
     */
    parameter?: string;
    /**
     * Additional properties specific to this error class.
     * @type {{ [key: string]: any; }}
     * @memberof CausingError
     */
    details?: { [key: string]: any; };
}

/**
 * Check if a given object implements the CausingError interface.
 */
export function instanceOfCausingError(value: object): value is CausingError {
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('errorCode' in value) || value['errorCode'] === undefined) return false;
    return true;
}

export function CausingErrorFromJSON(json: any): CausingError {
    return CausingErrorFromJSONTyped(json, false);
}

export function CausingErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): CausingError {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'],
        'errorCode': json['errorCode'],
        'parameter': json['parameter'] == null ? undefined : json['parameter'],
        'details': json['details'] == null ? undefined : json['details'],
    };
}

export function CausingErrorToJSON(value?: CausingError | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'description': value['description'],
        'errorCode': value['errorCode'],
        'parameter': value['parameter'],
        'details': value['details'],
    };
}

