/* tslint:disable */
/* eslint-disable */
/**
 * Routing OSM
 * With the Routing OSM service you can calculate routes from a list of waypoints for bicycles based on open street map data.
 *
 * The version of the OpenAPI document: 1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { PolylineFormat } from './PolylineFormat';
import {
    PolylineFormatFromJSON,
    PolylineFormatFromJSONTyped,
    PolylineFormatToJSON,
} from './PolylineFormat';

/**
 * 
 * @export
 * @interface Options
 */
export interface Options {
    /**
     * 
     * @type {PolylineFormat}
     * @memberof Options
     */
    polylineFormat?: PolylineFormat;
}

/**
 * Check if a given object implements the Options interface.
 */
export function instanceOfOptions(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function OptionsFromJSON(json: any): Options {
    return OptionsFromJSONTyped(json, false);
}

export function OptionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): Options {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'polylineFormat': !exists(json, 'polylineFormat') ? undefined : PolylineFormatFromJSON(json['polylineFormat']),
    };
}

export function OptionsToJSON(value?: Options | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'polylineFormat': PolylineFormatToJSON(value.polylineFormat),
    };
}

