/* tslint:disable */
/* eslint-disable */
/**
 * Routing OSM
 * With the Routing OSM service you can calculate routes from a list of waypoints based on open street map data.
 *
 * The version of the OpenAPI document: 1.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PolylineFormat } from './PolylineFormat';
import {
    PolylineFormatFromJSON,
    PolylineFormatFromJSONTyped,
    PolylineFormatToJSON,
} from './PolylineFormat';

/**
 * 
 * @export
 * @interface Options
 */
export interface Options {
    /**
     * 
     * @type {PolylineFormat}
     * @memberof Options
     */
    polylineFormat?: PolylineFormat;
}



/**
 * Check if a given object implements the Options interface.
 */
export function instanceOfOptions(value: object): value is Options {
    return true;
}

export function OptionsFromJSON(json: any): Options {
    return OptionsFromJSONTyped(json, false);
}

export function OptionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): Options {
    if (json == null) {
        return json;
    }
    return {
        
        'polylineFormat': json['polylineFormat'] == null ? undefined : PolylineFormatFromJSON(json['polylineFormat']),
    };
}

export function OptionsToJSON(value?: Options | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'polylineFormat': PolylineFormatToJSON(value['polylineFormat']),
    };
}

