/* tslint:disable */
/* eslint-disable */
/**
 * Routing OSM
 * With the Routing OSM service you can calculate routes from a list of waypoints based on open street map data.
 *
 * The version of the OpenAPI document: 1.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * The result of the reachable areas calculation.
 * @export
 * @interface ReachableAreas
 */
export interface ReachableAreas {
    /**
     * The list of polygons calculated for the specified horizons in GeoJson format. For each horizon there is a separate polygon at the same index.
     * @type {Array<string>}
     * @memberof ReachableAreas
     */
    polygons: Array<string>;
}

/**
 * Check if a given object implements the ReachableAreas interface.
 */
export function instanceOfReachableAreas(value: object): value is ReachableAreas {
    if (!('polygons' in value) || value['polygons'] === undefined) return false;
    return true;
}

export function ReachableAreasFromJSON(json: any): ReachableAreas {
    return ReachableAreasFromJSONTyped(json, false);
}

export function ReachableAreasFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReachableAreas {
    if (json == null) {
        return json;
    }
    return {
        
        'polygons': json['polygons'],
    };
}

export function ReachableAreasToJSON(value?: ReachableAreas | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'polygons': value['polygons'],
    };
}

