/* tslint:disable */
/* eslint-disable */
/**
 * Routing OSM
 * With the Routing OSM service you can calculate routes from a list of waypoints based on open street map data.
 *
 * The version of the OpenAPI document: 1.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * The result of the reachable areas calculation.
 * @export
 * @interface ReachableAreas
 */
export interface ReachableAreas {
    /**
     * The list of polygons calculated for the specified horizons in GeoJson format. For each horizon there is a separate polygon at the same index.
     * @type {Array<string>}
     * @memberof ReachableAreas
     */
    polygons: Array<string>;
}

/**
 * Check if a given object implements the ReachableAreas interface.
 */
export function instanceOfReachableAreas(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "polygons" in value;

    return isInstance;
}

export function ReachableAreasFromJSON(json: any): ReachableAreas {
    return ReachableAreasFromJSONTyped(json, false);
}

export function ReachableAreasFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReachableAreas {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'polygons': json['polygons'],
    };
}

export function ReachableAreasToJSON(value?: ReachableAreas | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'polygons': value.polygons,
    };
}

