/* tslint:disable */
/* eslint-disable */
/**
 * Routing OSM
 * With the Routing OSM service you can calculate routes from a list of waypoints based on open street map data.
 *
 * The version of the OpenAPI document: 1.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { DrivingDirection } from './DrivingDirection';
import {
    DrivingDirectionFromJSON,
    DrivingDirectionFromJSONTyped,
    DrivingDirectionToJSON,
} from './DrivingDirection';

/**
 * 
 * @export
 * @interface ReachableOptions
 */
export interface ReachableOptions {
    /**
     * 
     * @type {DrivingDirection}
     * @memberof ReachableOptions
     */
    drivingDirection?: DrivingDirection;
}

/**
 * Check if a given object implements the ReachableOptions interface.
 */
export function instanceOfReachableOptions(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ReachableOptionsFromJSON(json: any): ReachableOptions {
    return ReachableOptionsFromJSONTyped(json, false);
}

export function ReachableOptionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReachableOptions {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'drivingDirection': !exists(json, 'drivingDirection') ? undefined : DrivingDirectionFromJSON(json['drivingDirection']),
    };
}

export function ReachableOptionsToJSON(value?: ReachableOptions | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'drivingDirection': DrivingDirectionToJSON(value.drivingDirection),
    };
}

